name: IysCodeMovil
options:
  bundleIdPrefix: dev.iyscode
  deploymentTarget:
    iOS: "16.4"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "16.4"
    PRODUCT_NAME: IysCodeMovil
    GENERATE_INFOPLIST_FILE: NO
    CURRENT_PROJECT_VERSION: "7"
    MARKETING_VERSION: "0.5.2"

targets:
  IysCodeMovilCore:
    type: framework.static
    platform: iOS
    sources:
      - path: Sources
        type: group
        excludes:
          - IysCodeMovilApp.swift
    settings:
      base:
        PRODUCT_NAME: IysCodeMovilCore
        PRODUCT_BUNDLE_IDENTIFIER: dev.iyscode.movil.core
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        SKIP_INSTALL: YES
    dependencies:
      - framework: .build/llama/llama.xcframework
        embed: false
        codeSign: false

  IysCodeMovil:
    type: application
    platform: iOS
    sources:
      - path: App
        type: group
        excludes:
          - LaunchScreen.storyboard
      - path: Assets.xcassets
      - path: LocalPacks
        type: folder
    dependencies:
      - target: IysCodeMovilCore
      - framework: .build/llama/llama.xcframework
        embed: true
        codeSign: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.iyscode.movil
        PRODUCT_NAME: IysCodeMovil
        DEFINES_MODULE: NO
        CODE_SIGNING_ALLOWED: YES
        CODE_SIGNING_REQUIRED: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: Info.plist

  IysCodeMovilTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        type: group
    dependencies:
      - target: IysCodeMovilCore
      - framework: .build/llama/llama.xcframework
        embed: false
        codeSign: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.iyscode.movil.tests
        PRODUCT_NAME: IysCodeMovilTests
        DEFINES_MODULE: NO
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

schemes:
  IysCodeMovil:
    build:
      targets:
        IysCodeMovilCore: all
        IysCodeMovil: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - IysCodeMovilTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
